Repository 1024pix/pix-db-replication, pull requests merged in 2021-01, with the labels that each got.

#69 [TECH] Supprimer les dépendances plus utilisées
  package-lock.json
  package.json
Labels: Tech Review OK

#70 [TECH] Passer de node 14.15.0 à 14.15.4
  .circleci/config.yml
  .nvmrc
  package.json
Labels: :speech_balloon: Tech Review Needed

#68 [TECH] Mise à jour des dépendances
  package-lock.json
  package.json
Labels: Tech Review OK

#71 [TECH] Mettre à jour l'image docker de postgresql utilisée par la CI
  .circleci/config.yml
Labels: :speech_balloon: Tech Review Needed, cross-team

#65 Ne pas restaurer les snapshot de KE pour les internes
  steps.js
  test/integration/steps_test.js
  test/integration/test-helper.js
  test/unit/steps_test.js
Labels: :speech_balloon: Tech Review Needed, improvement

#72 [TECH] Faciliter le développement en local en disposant d'une BDD alimentée.
  README.md
  docker-compose.yml
  local-setup/data/source.pgsql
  local-setup/data/target.pgsql
  local-setup/script/create-databases.sh
  local-setup/script/create-databases.sql
  local-setup/script/load-databases.sh
  package.json
  sample.env
  src/extract-configuration-from-environment.js
  src/run-replicate-incrementally.js
Labels: :speech_balloon: Tech Review Needed, cross-team

#73 Grouper le code de production dans un dossier dédié
  Procfile
  README.md
  src/airtable-data.js
  src/db-connection.js
  src/enrichment.js
  src/logger.js
  src/replicate-incrementally.js
  src/replication_job.js
  src/run-replicate-incrementally.js
  src/run.js
  src/steps.js
  test/integration/enrichment_test.js
  test/integration/replicate-incrementally-test.js
  test/integration/steps_test.js
  test/unit/steps_test.js
Labels: :speech_balloon: Tech Review Needed, cross-team

#74 Ajouter des tests d'acceptance
  sample.env
  test/acceptance/full-dump-replication.js
Labels: :speech_balloon: Tech Review Needed, cross-team

#77 [TECH] Tracer l'origine des promesses rejetées.
  src/replication_job.js
  src/run-replicate-incrementally.js
  src/run.js
  src/schedule-incremental-replication.js
Labels: :speech_balloon: Tech Review Needed, cross-team

#78 [TECH] Détailler et corriger les instructions de relance.
  README.md
Labels: :speech_balloon: Tech Review Needed

#79 [TECH] Implémenter correctement l'installation asynchrone du client de BDD
  src/steps.js
Labels: :speech_balloon: Tech Review Needed
