Repository 1024pix/pix-db-replication, pull requests merged in 2022-03, with the labels that each got.

#106 [FEATURE] Mise a jour de la réplication de la relation challenge -> skill
  src/replicate-learning-content.js
Labels: cross-team, :rocket: Ready to Merge, :speech_balloon: Tech Review Needed

#107 [CLEANUP] Renommage d'une variable pour plus de clarté
  src/steps.js
Labels: cross-team, :rocket: Ready to Merge, :speech_balloon: Tech Review Needed

#108 [TECH] Ajouter une vue pour la table schooling registrations (PIX-4491).
  src/create-views-for-missing-tables.js
  src/enrichment.js
  src/steps.js
  test/acceptance/full-dump-replication-test.js
  test/integration/create-views-for-missing-tables-test.js
  test/integration/enrichment_test.js
Labels: :rocket: Ready to Merge, Tech Review OK

#109 [CLEANUP] Renomme un script
  README.md
  package.json
Labels: :rocket: Ready to Merge, :speech_balloon: Tech Review Needed
