Repository 1024pix/pix-db-replication, pull requests merged in 2023-03, with the labels that each got.

#137 :sparkles: Fetch CPF formations list from open data
  cpf/scripts/fetch-cpf-formations.sh
  cron.json
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK, team-captains

#138 [TECH] Générer un recordid unique à partir de plusieurs champs
  cpf/scripts/fetch-cpf-formations.sh
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK, team-captains

#139 [TECH] Mise à jour vers node 18
  .circleci/config.yml
  package-lock.json
  package.json
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK, team-captains

#140 [TECH] Mise à jour des dépendances
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-captains

#142 [TECH] Ajout de renovate
  .github/renovate.json
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#156 [TECH] Corriger l'export des données CPF depuis l'open data
  cpf/README.md
  cpf/create-table.sql
  cpf/docker-compose.yml
  cpf/scripts/fetch-cpf-formations.sh
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK, team-captains, no-review-app

#160 [TECH] Refactorise quelques parties de la réplication
  README.md
  src/main.js
  src/steps/incremental.js
  test/integration/steps/incremental_test.js
  test/utils/database.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-captains
