Repository 1024pix/pix-db-replication, pull requests merged in 2023-02, with the labels that each got.

#126 Monter la version de PG de 13 à 14
  .circleci/config.yml
  docker-compose.yml
Labels: :rocket: Ready to Merge, Tech Review OK, team-captains

#130 [BUGFIX] Correction de l'extraction de l'attribut name des compétences
  src/replicate-learning-content.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-captains

#129 [TECH] Ajouter des champs aux épreuves récupérés depuis LCMS (PIX-7110).
  src/replicate-learning-content.js
Labels: :rocket: Ready to Merge, Tech Review OK

#133 [BUGFIX] Revert du rajout des champs dans les épreuves
  src/replicate-learning-content.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-captains

#132 [FEATURE] Mise a jour de la version par défaut de pg
  src/config/extract-configuration-from-environment.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-captains

#136 [FEATURE] Ajouter des champs aux épreuves récupérés depuis LCMS
  src/replicate-learning-content.js
Labels: :rocket: Ready to Merge

#134 [BUGFIX] Rajout d'un timeout sur la requête LCMS
  src/lcms-client.js
  test/unit/lcms-client_test.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK, team-captains
