Repository 1024pix/pix-db-replication, pull requests merged in 2023-01, with the labels that each got.

#125 [TECH] Met à jour la facon de récupérer le titre fr d'une compétence
  src/replicate-learning-content.js
  test/utils/mock-lcms-get-airtable.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK, team-captains

#127 Revert "[TECH] Met à jour la facon de récupérer le titre fr d'une compétence"
  src/replicate-learning-content.js
  test/utils/mock-lcms-get-airtable.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-captains

#128 Revert "Revert "[TECH] Met à jour la facon de récupérer le titre fr d'une compétence""
  src/replicate-learning-content.js
  test/utils/mock-lcms-get-airtable.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK
