Repository 1024pix/pix-db-replication, pull requests merged in 2025-06, with the labels that each got.

#312 [BUGFIX] Corriger le setup local des BDD
  local-setup/script/create-databases.sql
Labels: cross-team, :rocket: Ready to Merge

#311 [DOCS] Ajoute 2 infos dans le readme pour dev sur l'env local
  README.md
Labels: cross-team, :rocket: Ready to Merge

#309 [FEATURE] Inclure les métadonnées de modules dans pix-datawarehouse-production (PIX-17912)
  src/main.js
  src/steps/index.js
  src/steps/modulix-learning-content/index.js
  src/steps/modulix-learning-content/lcms-client.js
  test/acceptance/full-dump-replication-test.js
  test/integration/steps/modulix-learning-content/index_test.js
  test/unit/steps/modulix-learning-content/index_test.js
  test/unit/steps/modulix-learning-content/lcms-client_test.js
  test/utils/mock-modulix-lcms-content.js
Labels: :rocket: Ready to Merge

#317 [BUGFIX] Répliquer les données des modules périodiquement.
  src/main.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#318 [TECH] Ajout des horodatages de changement de statut pour les acquis
  src/steps/learning-content/index.js
Labels: :rocket: Ready to Merge, Tech Review OK

#320 [TECH] Message d'erreur plus explicite lorsqu'un des objets de la réplication n'a pas de clé primaire
  src/errors.js
  test/unit/errors_test.js
Labels: :rocket: Ready to Merge, Tech Review OK
