Repository 1024pix/pix-db-replication, pull requests merged in 2025-01, with the labels that each got.

#280 [FEATURE] Ajouter les tables frameworks, thematics et missions dans la réplication (PIX-15883)
  src/steps/learning-content/index.js
  test/acceptance/full-dump-replication-test.js
  test/unit/steps/learning-content/index_test.js
  test/utils/mock-lcms-get-airtable.js
Labels: cross-team, :rocket: Ready to Merge, Tech Review OK

#282 [TECH] Mise à jour de bull-repl.
  README.md
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech Review OK, team-captains

#283 [Fix] thematics table schema and add learning content replication logs
  src/database-helper.js
  src/errors.js
  src/steps/learning-content/index.js
Labels: :rocket: Ready to Merge, Tech Review OK

#286 [TECH] Ajout de log lors des opérations de backup / restore.
  src/steps/backup-restore/index.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-captains

#285 [TECH] Mise à jour du script de parsing des logs.
  README.md
  utils/parse-replication-logs.js
Labels: :rocket: Ready to Merge, Tech Review OK, team-captains

#287 [FEATURE] Ajout des informations manquantes pour la table tutorials, source - format - duration
  src/steps/learning-content/index.js
Labels: cross-team, :rocket: Ready to Merge
